jjrom/resto

include/resto/RestoFeature.php

Fix bug RestoFeature

---

include/resto/Drivers/PostgreSQL/Functions_rights.php
include/resto/Drivers/RestoDatabaseDriver_PostgreSQL.php
include/resto/Modules/Admin.php
include/resto/RestoDatabaseDriver.php

-> POST a new group
-> PUT group right
-> GET group rights

Add groups administration

---

include/resto/Drivers/PostgreSQL/Functions_collections.php
include/resto/RestoCollection.php

-> update function Functions_collections::removeCollection

 Add default rights deleting when collection is deleted

---

_install/installDB.sh
include/resto/Drivers/PostgreSQL/Functions_users.php
include/resto/Drivers/RestoDatabaseDriver_PostgreSQL.php
include/resto/Modules/Admin.php

Add route to administrate groups
Add filters when getting users profiles
Change the groups column type in user table

Update for administration

---

include/resto/RestoCollection.php

When trying to create a collection from JSON object, check if JSON object contains osDescription and osDescription.en sections

Add JSON object checking at collection creation time

---

include/resto/Routes/RestoRouteGET.php

This avoid non existing object error

Add definition of $user even if it is null

---

include/resto/Routes/RestoRouteGET.php

user->getUserSignatures instead of user->getSignatures

Fix bug, call to undefined function

---

include/resto/Drivers/PostgreSQL/Functions_cart.php
include/resto/Routes/RestoRouteDELETE.php

-> return false when no item is deleted in database
-> secure array calls

2 modifcications in Cart item deletion process

---

include/resto/RestoUser.php
include/resto/Utils/RestoGeometryUtil.php

Fix bug in RestoGeometryUtil::getExtent

---

include/resto/RestoFeature.php
include/resto/RestoLicense.php
include/resto/RestoOrder.php
include/resto/XML/RestoMetalink.php

Now, success and errors are returned. In case of errors, explanations and ways to resolve errors are given.
I'm not sure of RestoFeature::getLicense wanted behavior... So I leave code in comments

Change content of order download response when JSON formating is requested

---

include/resto/Routes/RestoRouteGET.php
include/resto/Utils/RestoWMSUtil.php

1. delete user validation check before wms streaming
2. decode url param before using it with curl call

Update wms streaming

---

include/resto/Modules/Admin.php

Use RestoContext query parameters instead of filter_input method

Update way to get query parameters in Admin module

---

include/resto/Drivers/PostgreSQL/Functions_features.php

Wrong value taken in json for 'uid' field in methods : storeKeywordsFacets and removeFeatureFacets

Correct issue https://github.com/jjrom/resto/issues/210

---

include/resto/RestoFeatureCollection.php

Fix PHP Notice: Undefined variable: gazetteer (line 751) and line endings to unix style (LF)

Fix PHP Notice: Undefined variable: gazetteer

---

.gitattributes

Force all text files pushed to repo by any user to have LF line endings

.gitattributes - Force LF for all files

---

include/resto/RestoModel.php

New searchFilters for all models: publishedAfter & publishedBefore

New searchFilters: publishedAfter & publishedBefore

---

include/resto/Drivers/PostgreSQL/Functions_history.php
include/resto/RestoUser.php
include/resto/Routes/RestoRouteGET.php

New Feature: User can view his search queries

[Feature] User Search Queries API

---

include/resto/RestoFeatureCollection.php

It also fix PHP Fatal error of atom feed when filters are used

PHP Notice bugfix "Trying to get property of non-object"

---

include/resto/Drivers/PostgreSQL/Functions_features.php

If estimated count is lower then number of results for 10 pages of default size perform exact count.
Example of query:
http://resto.mapshup.com/2.2/api/collections/search.json?updated=2016-06-01&q=poland&cloudCover=[0,20]
On first page claims 20 results but it has (currently) 164 results :)
http://resto.mapshup.com/2.2/api/collections/search.json?updated=2016-06-01&q=poland&cloudCover=[0,20]&page=9

Perform exact count of search results if estimation is small

---

include/resto/RestoUser.php

Should be ```min()``` not ```max()``` :D

Bugfix in user search queris API

---

build/resto-database/installDB.sh
config.env
deploy
docker-compose-nodb.dev.yml
docker-compose-restodb.yml
docker-compose.yml
scripts/createAdminUser.sh
scripts/createUser.sh
undeploy

Modifications to plug an existing database instead of deploying a Docker-based PG instance

Allows using an external database instead of Docker-provided one

---

app/resto/core/RestoCollection.php
app/resto/core/RestoCollections.php
app/resto/core/addons/STAC.php
app/resto/core/api/CollectionsAPI.php
app/resto/core/api/ServicesAPI.php
app/resto/core/dbfunctions/CollectionsFunctions.php
app/resto/core/models/SatelliteModel.php
examples/collections/L8.json
examples/collections/S2.json

Stac 1.0.0 rc1

---

app/resto/core/Resto.php
app/resto/core/RestoCollection.php
app/resto/core/RestoFeatureCollection.php
app/resto/core/addons/STAC.php
app/resto/core/api/CollectionsAPI.php
app/resto/core/dbfunctions/FacetsFunctions.php
app/resto/core/models/OpticalModel.php
app/resto/core/models/SatelliteModel.php
app/resto/core/utils/RestoFeatureUtil.php
app/resto/core/xml/OSDD.php

Merge stac-1.0.0-rc.3 branch into master

Stac 1.0.0 rc.3

---

app/resto/core/RestoModel.php
app/resto/core/utils/RestoFeatureUtil.php
app/resto/core/utils/RestoGeometryUtil.php

* Rename feature property "keywords" to "resto:keywords"
* Add "resto:internal" property (not displayed in API output)

Update for SARA requirements

---

app/resto/core/Resto.php
app/resto/core/RestoCollections.php
app/resto/core/RestoFeatureCollection.php
app/resto/core/RestoModel.php
app/resto/core/RestoQueryAnalyzer.php
app/resto/core/addons/STAC.php
app/resto/core/api/FeaturesAPI.php
app/resto/core/api/ServicesAPI.php
app/resto/core/dbfunctions/FiltersFunctions.php
app/resto/core/models/DefaultModel.php

Correct issues #268, #269, #270, #267

Correct format issues

---

app/resto/core/RestoCollection.php
app/resto/core/RestoModel.php
app/resto/core/addons/Tag.php
app/resto/core/dbfunctions/CollectionsFunctions.php
examples/collections/L8.json
examples/collections/S2.json

* [STAC] Returns license property in collection (instead of licenseId)
* [STAC] Remove self, root, parent, child, item and items links from input collection
* Pass planet info to Tag add-on (read from STAC ssys:targets property)

Bunch of updates

---

app/resto/core/RestoCollections.php
app/resto/core/RestoModel.php
app/resto/core/addons/STAC.php
app/resto/core/api/CollectionsAPI.php
app/resto/core/api/FeaturesAPI.php
app/resto/core/dbfunctions/CollectionsFunctions.php
app/resto/core/dbfunctions/FacetsFunctions.php
app/resto/core/dbfunctions/FeaturesFunctions.php
app/resto/core/dbfunctions/FiltersFunctions.php
build/resto-database/sql/05_resto_indexes.sql

Both on /collections and /search endpoints)

Add "ck" query parameters to filters search on collection keywords

---

app/resto/core/Resto.php
app/resto/core/RestoFeatureCollection.php
app/resto/core/RestoModel.php
app/resto/core/RestoRouter.php
app/resto/core/dbfunctions/FacetsFunctions.php

Support both resto and STAC query filter name in search (e.g. "processingLevel" and "processing:level"

---

app/resto/core/dbfunctions/UsersFunctions.php
build/resto-database/Dockerfile
build/resto-database/container_root/cont-init.d/10-postgresql-conf.sh
build/resto-database/installDB.sh
build/resto-database/start-postgres.sh
build/resto/Dockerfile
build/resto/container_root/cont-init.d/09-php-opcache.sh
build/resto/container_root/cont-init.d/10-saml-config.sh
build/resto/container_root/cont-init.d/11-nginx-fastcgi.sh
build/resto/container_root/cont-init.d/15-resto-config.sh
build/resto/container_root/cont-init.d/16-resto-docs.sh
build/resto/container_root/cont-init.d/99-php-xdebug.sh
docker-compose-restodb.yml

* Upgrade resto to jjrom/nginx-fpm:8.1-1 
* Correct issue #339

Upgrade resto to jjrom/nginx-fpm:8.1-1 

---

app/resto/core/api/ServicesAPI.php

[[STAC] String property 'planet' replaced by ssys:targets array property](https://github.com/jjrom/resto/commit/c69911b3a5cd36ad3e198b13778c80eafaa8b177)

[STAC] String property 'planet' replaced by ssys:targets array property

---

build/resto/container_root/cont-init.d/15-resto-config.sh
config-dev.env
config.env
deploy
docker-compose.yml

Changes :
* Replace DATABASE_EXPOSED_PORT by DATABASE_PORT
* Remove access to database outside of container
**[IMPORTANT]** New DATABASE_PORT env parameter must be set on existing instance

Replace DATABASE_EXPOSED_PORT by DATABASE_PORT

---

app/resto/core/RestoCollection.php
app/resto/core/RestoCollections.php
app/resto/core/api/CollectionsAPI.php

This allow to assign a collection model at POST without modifying the input file description. Correct issue #374

Add a model parameter at the POST collection

---

app/resto/core/RestoCollection.php
app/resto/core/RestoModel.php
docker-compose.dev.yml
docker-compose.yml

...and [move postgresql.conf under /etc to avoid volume conflict with /var/lib/postgresql/data](https://github.com/jjrom/resto/commit/05772497a5c7714850f5d9fb678dcbf5d730ba7a)

Remove constraint on collection name

---

app/resto/core/RestoConstants.php
app/resto/core/RestoContext.php
app/resto/core/addons/STAC.php
app/resto/core/utils/STACUtil.php
build/resto/config.php.template
build/resto/container_root/cont-init.d/17-resto-database.php
config-dev.env
config.env
docs/resto-api.html
docs/resto-api.json
resto-database-model/02_resto_common_model.sql
resto-database-model/postInstall/01_inserts.sql

* Insert in database are performed after migration SQL scripts

* Add mergeRootCatalogLinks option (untested)

---

app/resto/core/RestoCollection.php
app/resto/core/dbfunctions/RightsFunctions.php
examples/collections/L8_nosummaries.json

* Do not return empty summaries in GET collections

* Correct PHP Warning in logs duing rights check

---

app/resto/core/dbfunctions/FeaturesFunctions.php

The feature creation when it already exists was broken

Fix typo in keysValues variable

---

app/resto/core/dbfunctions/CatalogsFunctions.php

Fix an issue where grand-children (and else) were not updated in base.

Update all catalog children

---

app/resto/core/RestoCollection.php
app/resto/core/RestoCollections.php
app/resto/core/RestoConstants.php
app/resto/core/RestoContext.php
app/resto/core/RestoFeature.php
app/resto/core/RestoModel.php
app/resto/core/RestoQueryAnalyzer.php
app/resto/core/addons/Cataloger.php
app/resto/core/api/STACAPI.php
app/resto/core/api/ServicesAPI.php
app/resto/core/dbfunctions/CatalogsFunctions.php
app/resto/core/dbfunctions/FiltersFunctions.php
app/resto/core/utils/JSONLDUtil.php
build/resto/config.php.template
config.env

Address this  https://github.com/radiantearth/stac-spec/issues/378
**Note : not activated by default. Change USE_JSONLD environment variable to true to activate it**

Add JSON-LD support

---

app/resto/core/RestoCollection.php
app/resto/core/RestoCollections.php
app/resto/core/RestoConstants.php
app/resto/core/api/STACAPI.php
app/resto/core/dbfunctions/CatalogsFunctions.php
app/resto/core/dbfunctions/FiltersFunctions.php
docs/COLLECTIONS_AND_CATALOGS.md
examples/collections/DummyCollection.json

[IMPORTANT] resto.catalog table should be wiped and reinvest

Allow to DELETE collection under a catalog

---

app/resto/core/RestoConstants.php
app/resto/core/api/STACAPI.php
app/resto/core/dbfunctions/FiltersFunctions.php
app/resto/core/utils/Lexer.php
app/resto/core/utils/RestoGeometryUtil.php

* Support BBOX interesection on CQL2
* Conformance classes aligned with stac-api-filter 1.0.0rc-4

* Correct issue #494
